/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.demobarcodescan;


import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LENOVO
 */
public class OrderForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OrderForm.class.getName());
    
    private DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    private String product_id, productName;
    private double price;
    private int qty;
    
            

    /**
     * Creates new form OrderForm
     */
    private DefaultTableModel tbl = new DefaultTableModel();
    public OrderForm() {
        initComponents();
        lbl_Date.setText(df.format(new Date()));
        txt_OrderId.setText("" + autoOrderId());
        TableModel();
        txt_OrderId.setEnabled(false);
    }
    
    private void TableModel() {
        tbl.addColumn("Product ID");
        tbl.addColumn("Product Name");
        tbl.addColumn("Price");
        tbl.addColumn("Qty");
        tbl.addColumn("Amount");
        tbl_oderDetail.setModel(tbl);
    }
    private int autoOrderId() {
    int id = 0;
    try (Connection con = ConnectDatabase.getConnection();
         PreparedStatement ps = con.prepareStatement("SELECT MAX(orderId) FROM [tbl_order]");
         ResultSet rs = ps.executeQuery()) {

        if (rs.next()) {
            id = rs.getInt(1);
        }
        id++;
    } catch (SQLException e) {
        e.printStackTrace(); // để bạn thấy lỗi gì xảy ra
    }
    return id;
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_OrderId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Barcode = new javax.swing.JTextField();
        txt_ProductName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Qty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_oderDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Date.setText("jLabel1");

        jLabel1.setText("Order ID");

        txt_OrderId.setToolTipText("");
        txt_OrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_OrderIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Barcode");

        txt_Barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BarcodeActionPerformed(evt);
            }
        });
        txt_Barcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_BarcodeKeyTyped(evt);
            }
        });

        txt_ProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ProductNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Product Name");

        jLabel4.setText("Price Out");

        txt_Price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PriceActionPerformed(evt);
            }
        });

        jLabel5.setText("Qty");

        txt_Qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QtyActionPerformed(evt);
            }
        });

        tbl_oderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_oderDetail);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Date)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_Date)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_OrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_OrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OrderIdActionPerformed

    private void txt_BarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BarcodeActionPerformed

    private void txt_ProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ProductNameActionPerformed

    private void txt_PriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PriceActionPerformed

    private void txt_QtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QtyActionPerformed
        String enter_qty = txt_Qty.getText();
        Double amount = Integer.valueOf(enter_qty) * price;
        String[] rows = {product_id, productName, ""+price, enter_qty, ""+amount}; 
        tbl.addRow(rows);
        tbl_oderDetail.setModel(tbl);
    }//GEN-LAST:event_txt_QtyActionPerformed

    private void txt_BarcodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_BarcodeKeyTyped
        // TODO add your handling code here:
        // Khi người dùng nhấn Enter
    if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
        String barcode = txt_Barcode.getText().trim();

        if (barcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập hoặc quét barcode!");
            return;
        }

//        String sql = "select p.p_id, p.productName, p.priceOut, s.Qty from tbl_product" + " where p.p_id = s.p_id and p.barcode = '"+txt_Barcode.getText()+"'";
            String sql = "SELECT p.p_id, p.productName, p.priceOut, ISNULL(s.Qty, 0) as Qty " +
             "FROM tbl_product p " +
             "LEFT JOIN tbl_stocks s ON p.p_id = s.p_id " +
             "WHERE p.barcode = ?";



        try (Connection conn = ConnectDatabase.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            
            ps.setString(1, barcode);
            
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    product_id = ""+rs.getInt(1);
                    productName = rs.getString(2);
                    price = rs.getDouble(3);
                    qty = rs.getInt(4);

                    if (qty > 0) {
                        txt_ProductName.setText(productName);
                        txt_Price.setText(""+price);
                        txt_Qty.requestFocus();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sản phẩm đã hết hàng!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm với barcode: " + barcode);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn DB: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_txt_BarcodeKeyTyped

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OrderForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Date;
    private javax.swing.JTable tbl_oderDetail;
    private javax.swing.JTextField txt_Barcode;
    private javax.swing.JTextField txt_OrderId;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_ProductName;
    private javax.swing.JTextField txt_Qty;
    // End of variables declaration//GEN-END:variables
}
